# Generated by Django 2.1.7 on 2019-02-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmarkup',
            name='markup_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
